spring.application.name=appointment-scheduling-api


spring.jpa.hibernate.ddl-auto=update

# Swagger Config
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Custom Metadata
application.description=API for dynamically scheduling doctor appointments
application.version=1.0